# https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/testing/opensbi-spacemit/APKBUILD
milkv_jupiter_opensbi:
  git:
    repo: "https://gitee.com/bianbu-linux/opensbi.git"
    version: "v2.0.2"
    checkout_dir: "/tmp/bianbu-opensbi"
  build_params:
    PLATFORM: generic
    ARCH: riscv
    CROSS_COMPILE: riscv64-linux-gnu-
    # CROSS_COMPILE: riscv64-unknown-linux-gnu-
    PLATFORM_DEFCONFIG: k1_defconfig

