starfive_visionfive2_kernel:
  target: "/tmp/kernel"
  download: https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-[version].tar.xz
  version: "6.12.5"
  dtb_file_location: /arch/riscv/boot/dts/starfive/jh7110-starfive-visionfive-2-v1.3b.dtb
  # do not use modules
  replace_m_for_y: true
  build_params:
    CROSS_COMPILE: riscv64-linux-gnu-
    ARCH: riscv
  add_to_config:
    # firmware in kernel
    CONFIG_EXTRA_FIRMWARE: "amdgpu/polaris10_ce.bin amdgpu/polaris10_ce_2.bin amdgpu/polaris10_k_smc.bin amdgpu/polaris10_k2_smc.bin amdgpu/polaris10_k_mc.bin amdgpu/polaris10_mc.bin amdgpu/polaris10_me.bin amdgpu/polaris10_me_2.bin amdgpu/polaris10_mec2.bin amdgpu/polaris10_mec2_2.bin amdgpu/polaris10_mec.bin amdgpu/polaris10_mec_2.bin amdgpu/polaris10_pfp.bin amdgpu/polaris10_pfp_2.bin amdgpu/polaris10_rlc.bin amdgpu/polaris10_sdma1.bin amdgpu/polaris10_sdma.bin amdgpu/polaris10_smc.bin amdgpu/polaris10_smc_sk.bin amdgpu/polaris10_uvd.bin amdgpu/polaris10_vce.bin amdgpu/dimgrey_cavefish_vcn.bin amdgpu/dimgrey_cavefish_ce.bin amdgpu/dimgrey_cavefish_pfp.bin amdgpu/dimgrey_cavefish_me.bin amdgpu/dimgrey_cavefish_mec.bin amdgpu/dimgrey_cavefish_mec2.bin amdgpu/dimgrey_cavefish_rlc.bin amdgpu/dimgrey_cavefish_sos.bin amdgpu/dimgrey_cavefish_ta.bin amdgpu/dimgrey_cavefish_sdma.bin amdgpu/dimgrey_cavefish_dmcub.bin amdgpu/dimgrey_cavefish_smc.bin radeon/CYPRESS_uvd.bin radeon/CEDAR_smc.bin radeon/CEDAR_me.bin radeon/CEDAR_pfp.bin radeon/CEDAR_rlc.bin amdgpu/hawaii_k_smc.bin amdgpu/hawaii_smc.bin amdgpu/hawaii_uvd.bin amdgpu/hawaii_vce.bin amdgpu/hawaii_sdma.bin amdgpu/hawaii_sdma1.bin amdgpu/hawaii_pfp.bin amdgpu/hawaii_me.bin amdgpu/hawaii_ce.bin amdgpu/hawaii_rlc.bin amdgpu/hawaii_mec.bin amdgpu/hawaii_mc.bin radeon/hawaii_pfp.bin radeon/hawaii_me.bin radeon/hawaii_ce.bin radeon/hawaii_mec.bin radeon/hawaii_mc.bin radeon/hawaii_rlc.bin radeon/hawaii_sdma.bin radeon/hawaii_smc.bin radeon/hawaii_k_smc.bin radeon/HAWAII_pfp.bin radeon/HAWAII_me.bin radeon/HAWAII_ce.bin radeon/HAWAII_mec.bin radeon/HAWAII_mc.bin radeon/HAWAII_mc2.bin radeon/HAWAII_rlc.bin radeon/HAWAII_sdma.bin radeon/HAWAII_smc.bin"
    CONFIG_EXTRA_FIRMWARE_DIR: "../linux-firmware"
    # needed for fedora: (zram)
    CONFIG_BLK_DEV_RAM: y
    CONFIG_BLK_DEV_RAM_COUNT: 16
    CONFIG_BLK_DEV_RAM_SIZE: 4096

    CONFIG_INPUT_EVDEV: y
    
    # AMDGPU + HDMI sound
    CONFIG_DRM_AMDGPU: y
    CONFIG_DRM_AMD_DC: y
    CONFIG_DRM_AMD_DC_FP: y
    CONFIG_SND_DYNAMIC_MINORS: y
    CONFIG_SND_MAX_CARDS: 32
    CONFIG_SND_VMASTER: y
    CONFIG_SND_HDA: y
    CONFIG_SND_HDA_INTEL: y
    CONFIG_SND_HDA_CODEC_HDMI: y
    CONFIG_SND_HDA_POWER_SAVE_DEFAULT: 0
    CONFIG_SND_HDA_CORE: y
    CONFIG_SND_HDA_COMPONENT: y
    CONFIG_SND_INTEL_NHLT: y
    CONFIG_SND_INTEL_DSP_CONFIG: y
    CONFIG_SND_INTEL_SOUNDWIRE_ACPI: y

    # needed for ubuntu (snap):
    CONFIG_SQUASHFS: y
    CONFIG_SQUASHFS_FILE_CACHE: y
    CONFIG_SQUASHFS_DECOMP_SINGLE: y
    CONFIG_SQUASHFS_COMPILE_DECOMP_SINGLE: y
    CONFIG_SQUASHFS_ZLIB: y
    CONFIG_SQUASHFS_LZ4: y
    CONFIG_SQUASHFS_LZO: y
    CONFIG_SQUASHFS_XZ: y
    CONFIG_SQUASHFS_ZSTD: y
    CONFIG_SQUASHFS_FRAGMENT_CACHE_SIZE: 3