---
- hosts: localhost
  vars:
    build_jobs: 16
    target: /dev/sdb
    on_boot:
      boot:
        device: "mmc 0"
        partition: 5
      rootfs_location: "/dev/mmcblk1p6"
      ramdisk_addr_r: "0x21000000"
      fdt_addr_r: "0x31000000"
    opensbi: "{{ milkv_jupiter_opensbi }}"
    u_boot: "{{ milkv_jupiter_u_boot }}"
    kernel: "{{ milkv_jupiter_kernel }}"
  tasks:
    - include_tasks: tasks/build-opensbi.yaml
    - include_tasks: tasks/build-u-boot.yaml
    - include_tasks: tasks/build-kernel.yaml
    
    - include_tasks: tasks/k1-clear-and-create-boot-partitions.yaml
    - include_tasks: tasks/k1-write-to-boot-partitions.yaml
    - include_tasks: tasks/create-bootfs-partition.yaml
    - include_tasks: tasks/create-opensuse-partition.yaml
    - include_tasks: create-and-copy-boot-src-to-boot-partition.yaml
    - include_tasks: tasks/copy-kernel-to-drive.yaml
