---
- hosts: localhost
  vars:
    kernel: "{{ starfive_visionfive2_kernel }}"
    target: /dev/sdb
    on_boot:
      boot:
        device: "mmc 1"
        partition: 3
      rootfs_location: "/dev/mmcblk1p4"
  tasks:
    - include_tasks: tasks/create-opensuse-partition.yaml
    - include_tasks: tasks/create-and-copy-boot-src-to-boot-partition.yaml
