---
- hosts: localhost
  vars:
    build_jobs: 16
    target: /dev/sdb
    on_boot:
      boot_device: "mmc 1"
      rootfs_location: "/dev/mmcblk1p3"
    opensbi: "{{ starfive_visionfive2_opensbi }}"
    u_boot: "{{ starfive_visionfive2_u_boot }}"
    kernel: "{{ starfive_visionfive2_kernel }}"
  tasks:

    - name: First compile code
      ansible.builtin.import_playbook: starfive-visionfive2-compile.yaml

    - include_tasks: tasks/clear-and-create-boot-partitions.yaml
    - include_tasks: tasks/write-to-boot-partitions.yaml
    - include_tasks: tasks/create-bootfs-partition.yaml
    - include_tasks: tasks/copy-kernel-to-drive.yaml
