---
- hosts: localhost
  vars:
    build_jobs: 16
    target: /dev/sdb
    on_boot:
      boot_device: "mmc 1"
      rootfs_location: "/dev/mmcblk1p3"
    opensbi: "{{ starfive_visionfive2_opensbi }}"
    u_boot: "{{ starfive_visionfive2_u_boot }}"
    kernel: "{{ starfive_visionfive2_kernel }}"
  tasks:
    - include_tasks: tasks/build-opensbi.yaml    
    - include_tasks: tasks/build-u-boot.yaml
    - include_tasks: tasks/build-kernel.yaml
