---
- name: First compile code
  ansible.builtin.import_playbook: starfive-visionfive2-compile.yaml

- hosts: localhost
  vars:
    build_jobs: 16
    target: /dev/sdb
    opensbi: "{{ starfive_visionfive2_opensbi }}"
    u_boot: "{{ starfive_visionfive2_u_boot }}"
    kernel: "{{ starfive_visionfive2_kernel }}"
  tasks:
    - include_tasks: tasks/jh7110-write-to-boot-partitions.yaml
    - include_tasks: tasks/copy-kernel-to-drive.yaml
